default: &default
  secret_key_base: 56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4
  email_interceptor_recipients: ""
  google_oauth2_key: "916030011848-h4mq2difs10nq0tj9f4nvu3mqnednrmu.apps.googleusercontent.com"
  google_oauth2_secret: "oOx2ZYhzpGgY0O4e6uQ_craO" 
  facebook_key: "382128139615782"
  facebook_secret: "fcfe8167ccb463071f19c8e665f4e0f6"
  rollbar_server_token: "19fef1c7d3ee4865b5e2b6709ae2afa3"
  # newrelic_key: "NRAA-53f5d6e23bb5b7f49f9ef93bf25"


maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  microsoft_api_key: ""
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

aws: &aws
  aws_s3_region: <%= ENV["AWS_S3_REGION"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket: <%= ENV["S3_BUCKET_NAME"] %>
  aws_s3_host_name: <%= ENV["AWS_S3_HOSTNAME"] %>
  
http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  <<: *default
  <<: *maps
  <<: *aws

test:
  <<: *default
  <<: *maps

staging:
  # secret_key_base: ""
  # server_name: ""
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  # force_ssl: true
  # delay_jobs: true
  # rollbar_server_token: ""
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: <%= ENV['DOMAIN'] %>
  mailer_delivery_method: :smtp
  smtp_settings:
    address: "smtp.gmail.com"
    port: 587
    domain: <%= ENV['DOMAIN'] %>
    user_name: <%= ENV['GMAIL_USERNAME'] %>
    password:  <%= ENV['GMAIL_PASSWORD'] %>
    authentication: :plain
    enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  secret_key_base: ""
  server_name: ""
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  server_name: "consul-egov.herokuapp.com"
  mailer_delivery_method: :smtp
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "consul-egov.herokuapp.com"
    :user_name: "consuldevbelgium@gmail.com"
    :password: "vBxgFW2eHwidZGz"
    :authentication: :plain
    :enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: "19fef1c7d3ee4865b5e2b6709ae2afa3"
  # secret_key_base: "44ec47b2c9a2577261c9706873917545b82839a329eec9920f58d4edc5c9bdf35f18b0fb5b211e4be4fda9c8f45fa667fd867d2a29c3cecf4eafa27812f92b1b"
  
  # secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  # server_name: <%= ENV['DOMAIN'] %>
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   address: "smtp.gmail.com"
  #   port: 587
  #   domain: <%= ENV['DOMAIN'] %>
  #   user_name: <%= ENV['GMAIL_USERNAME'] %>
  #   password:  <%= ENV['GMAIL_PASSWORD'] %>
  #   authentication: :plain
  #   enable_starttls_auto: true
  # force_ssl: true
  # delay_jobs: true
  # rollbar_server_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: "382128139615782"
  facebook_secret: "fcfe8167ccb463071f19c8e665f4e0f6"
  google_oauth2_key: "916030011848-h4mq2difs10nq0tj9f4nvu3mqnednrmu.apps.googleusercontent.com"
  google_oauth2_secret: "oOx2ZYhzpGgY0O4e6uQ_craO"
  # facebook_key: ""
  # facebook_secret: ""
  # google_oauth2_key: ""
  # google_oauth2_secret: ""
  # wordpress_oauth2_key: ""
  # wordpress_oauth2_secret: ""
  # wordpress_oauth2_site: ""
  <<: *maps
  <<: *apis
  <<: *aws
